#!/bin/bash

# Creates a new ~/.bin full of useful scripts for OSX
# Also updates ~/.bash_profile with useful aliases and corrects $PATH.
# Also checks and corrects user permissions for ~/.bin and ~/.bash_profile

echo ''
echo 'please confirm your username I am pretty sure your are:' $USER 'but want to be sure'
read $UNNAME
# backup ~/.bin if it already exists

test -d "/Users/$UNNAME/.bin" && sudo mv /Users/$UNNAME/.bin /Users/$UNNAME/.bin_old && echo 'Backed up your old ~/.bin to ~/.bin_old' || echo 'No need to move old ~/.bin as it does not exist'

# pause for 2 seconds
sleep 2

# create new ~/.bin

mkdir /Users/$UNNAME/.bin
echo ''
echo 'Copying the scripts to ~/.bin'
sudo cp -a scripts/* /Users/$UNNAME/.bin/
echo ''

# pause for 2 seconds
sleep 2

###########################
## UPDATE BASH PROFILE
############################

# if ~/.bash_profile exists then it backit up
test -d "/Users/$UNNAME/.bash_profile" && sudo mv /Users/$UNNAME/.bash_profile /Users/$UNNAME/.bash_profile_old && echo 'Backed up your old ~/.bash_profile to ~/.bash_profile_old' || echo 'No need to move old ~/.bash_profile as it does not exist'

# Copy the bash_profile-template to /Users/$UNNAME/.bash_profile
sudo cp scripts/bash_profile-template /Users/$UNNAME/.bash_profile

# Pause for 2 seconds
sleep 2

# Set correct permissions
echo ''
echo 'Setttng permissions so that $UNNAME is owner and can read, write and execute'
sudo chown -R $UNNAME /Users/$UNNAME/.bin
sudo chmod -R 750 /Users/$UNNAME/.bin
sudo chown $UNNAME /Users/$UNNAME/.bash_profile
sudo chmod 750 /Users/$UNNAME/.bash_profile
echo ''
sleep 2
echo '***********************************************************************************'
echo ''
echo 'Your ~/.bash_profile has been updated'
echo 'Type printprofile to read your bash_profile'
echo 'Type listbin to list the scripts in ~/.bin'
echo ''
echo '***********************************************************************************'
# pause for 2 second
echo ''
read -s -n 1 -p "Press any key to continue"
echo ''
echo 'Thanks, Bye.'
echo ''
