#!/bin/bash
# Sets all network connections down

echo ""
echo "setting all network connections down"
sudo -v
sleep 2
sudo ifconfig en0 down
sudo ifconfig en1 down
sudo ifconfig en2 down
sudo ifconfig p2p0 down
sudo ifconfig awdl0 down
sudo ifconfig bridge0 down
sudo ifconfig ipsec down
sudo ifconfig en4 down

echo  ""
echo "these network connections are up:"
echo ""
sudo ifconfig -lu